using SchedulingAssistant.Models;

namespace SchedulingAssistant.Services;

/// <summary>
/// Generates the next available section code for a given <see cref="SectionCodePattern"/>.
/// </summary>
public static class SectionCodeGenerator
{
    /// <summary>
    /// Maximum number of codes to try before giving up. Prevents unbounded loops when every
    /// code in a long sequence is already taken.
    /// </summary>
    private const int MaxAttempts = 500;

    /// <summary>
    /// Returns the first code in the pattern's sequence that is not already taken,
    /// or <c>null</c> if all codes within <see cref="MaxAttempts"/> are exhausted.
    /// </summary>
    /// <param name="pattern">The pattern defining the code structure and increment rule.</param>
    /// <param name="isCodeTaken">
    /// Predicate returning <c>true</c> when the given code already exists in the target
    /// course/semester. Typically a partial application of
    /// <c>ISectionRepository.ExistsBySectionCode</c>.
    /// </param>
    public static string? GetNextCode(SectionCodePattern pattern, Func<string, bool> isCodeTaken)
    {
        foreach (var candidate in EnumerateCodes(pattern))
        {
            if (!isCodeTaken(candidate))
                return candidate;
        }
        return null;
    }

    /// <summary>
    /// Returns the first few codes in the pattern's sequence for display as a preview.
    /// Used by the admin editor to verify the pattern looks correct before saving.
    /// </summary>
    /// <param name="pattern">The pattern to preview.</param>
    /// <param name="count">Number of example codes to return (default 3).</param>
    public static IReadOnlyList<string> GetPreviewCodes(SectionCodePattern pattern, int count = 3)
    {
        return EnumerateCodes(pattern).Take(count).ToList();
    }

    /// <summary>
    /// Returns <c>true</c> when <paramref name="code"/> could have been generated by
    /// <paramref name="pattern"/> — i.e. it matches the prefix/suffix and its incrementing
    /// part is reachable from the pattern's starting value.
    /// </summary>
    /// <param name="code">The section code to test (case-sensitive).</param>
    /// <param name="pattern">The pattern to match against.</param>
    public static bool MatchesPattern(string code, SectionCodePattern pattern)
    {
        var prefix = pattern.Prefix ?? string.Empty;
        var suffix = pattern.Suffix ?? string.Empty;

        if (!code.StartsWith(prefix, StringComparison.Ordinal)) return false;
        if (!code.EndsWith(suffix, StringComparison.Ordinal)) return false;

        int middleLength = code.Length - prefix.Length - suffix.Length;
        if (middleLength <= 0) return false;
        var middle = code.Substring(prefix.Length, middleLength);

        if (pattern.UseLetters)
        {
            // Incrementing part must be exactly one uppercase letter in [FirstLetter, 'Z'].
            return middle.Length == 1
                && middle[0] >= pattern.FirstLetter
                && middle[0] <= 'Z';
        }
        else
        {
            if (!long.TryParse(middle, out long value)) return false;
            if (value < (long)pattern.FirstNumber) return false;

            long diff = value - (long)pattern.FirstNumber;
            if (diff % pattern.Increment != 0) return false;

            // Verify the string representation matches exactly — distinguishes padded from
            // non-padded patterns (e.g. PadWidth=3 generates "001" not "1").
            string expected = pattern.PadWidth > 0
                ? value.ToString().PadLeft(pattern.PadWidth, '0')
                : value.ToString();
            return middle == expected;
        }
    }

    /// <summary>
    /// Lazily enumerates all codes in the sequence up to <see cref="MaxAttempts"/>.
    /// </summary>
    private static IEnumerable<string> EnumerateCodes(SectionCodePattern pattern)
    {
        if (pattern.UseLetters)
        {
            for (int i = 0; i < 26 && i < MaxAttempts; i++)
            {
                char letter = (char)(pattern.FirstLetter + i);
                if (letter > 'Z') yield break;
                yield return $"{pattern.Prefix}{letter}{pattern.Suffix}";
            }
        }
        else
        {
            for (int i = 0; i < MaxAttempts; i++)
            {
                long value = (long)pattern.FirstNumber + (long)pattern.Increment * i;
                string numStr = pattern.PadWidth > 0
                    ? value.ToString().PadLeft(pattern.PadWidth, '0')
                    : value.ToString();
                yield return $"{pattern.Prefix}{numStr}{pattern.Suffix}";
            }
        }
    }
}
