using System.Security.Cryptography;
using TermPoint.Licensing;
using Xunit;

namespace TermPoint.Tests;

/// <summary>
/// Verifies that <see cref="LicenseFulfillment.LicenseGenerator"/> produces license files
/// that pass validation by <see cref="LicenseValidator"/>. This is the critical round-trip
/// test for the fulfillment pipeline: if signing diverges even slightly from the CLI tool,
/// customers receive unusable licenses.
/// </summary>
public sealed class LicenseFulfillmentTests : IDisposable
{
    private readonly string _tempDir;
    private readonly RSA _rsa;
    private readonly string _privateKeyPem;
    private readonly string _publicKeyPem;

    public LicenseFulfillmentTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"fulfill_test_{Guid.NewGuid():N}");
        Directory.CreateDirectory(_tempDir);

        _rsa = RSA.Create(2048);
        _privateKeyPem = _rsa.ExportRSAPrivateKeyPem();
        _publicKeyPem = _rsa.ExportRSAPublicKeyPem();
    }

    public void Dispose()
    {
        _rsa.Dispose();
        try { Directory.Delete(_tempDir, recursive: true); } catch { }
    }

    private LicenseValidator CreateValidator(IClock clock)
        => new(_publicKeyPem, clock);

    private static IClock ClockAt(int year, int month, int day)
        => new FixedClock(new DateTime(year, month, day, 0, 0, 0, DateTimeKind.Utc));

    private void WriteLicenseFile(string content)
        => File.WriteAllText(Path.Combine(_tempDir, "termpoint.lic"), content);

    /// <summary>
    /// A license generated by LicenseFulfillment.LicenseGenerator should be accepted
    /// by the app's LicenseValidator as a valid, licensed state.
    /// </summary>
    [Fact]
    public void GeneratedLicense_ValidatesSuccessfully()
    {
        var content = LicenseFulfillment.LicenseGenerator.Generate(
            "Test Department", "Test University", expiryYears: 1, _privateKeyPem);

        WriteLicenseFile(content);

        var result = CreateValidator(ClockAt(2026, 7, 2)).ValidateLicenseFile(_tempDir);

        Assert.Equal(LicenseState.Licensed, result.State);
        Assert.Equal("Test Department", result.Department);
        Assert.Equal("Test University", result.Institution);
    }

    /// <summary>
    /// A license generated without an institution name should still validate,
    /// leaving Institution null (matches how older licenses behave).
    /// </summary>
    [Fact]
    public void GeneratedLicense_WithoutInstitution_ValidatesSuccessfully()
    {
        var content = LicenseFulfillment.LicenseGenerator.Generate(
            "Test Department", institution: null, expiryYears: 1, _privateKeyPem);

        WriteLicenseFile(content);

        var result = CreateValidator(ClockAt(2026, 7, 2)).ValidateLicenseFile(_tempDir);

        Assert.Equal(LicenseState.Licensed, result.State);
        Assert.Equal("Test Department", result.Department);
        Assert.Null(result.Institution);
    }

    /// <summary>
    /// The generated license should show as expired when validated after its expiry date.
    /// </summary>
    [Fact]
    public void GeneratedLicense_ExpiresCorrectly()
    {
        var content = LicenseFulfillment.LicenseGenerator.Generate(
            "Expiry Test Dept", institution: null, expiryYears: 1, _privateKeyPem);

        WriteLicenseFile(content);

        // Validate 2 years from now — should be expired
        var result = CreateValidator(ClockAt(2028, 7, 2)).ValidateLicenseFile(_tempDir);

        Assert.Equal(LicenseState.Expired, result.State);
        Assert.Equal("Expiry Test Dept", result.Department);
    }

    /// <summary>
    /// Tampering with the license content should cause validation to fail.
    /// </summary>
    [Fact]
    public void TamperedLicense_FailsValidation()
    {
        var content = LicenseFulfillment.LicenseGenerator.Generate(
            "Tamper Test Dept", institution: null, expiryYears: 1, _privateKeyPem);

        // Corrupt the base64 payload line (not the comment header).
        // Find the first non-comment, non-blank line — that's the payload.
        var lines = content.Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            var trimmed = lines[i].TrimEnd('\r').Trim();
            if (trimmed.Length > 0 && !trimmed.StartsWith('#'))
            {
                // Flip one character in the base64 payload
                var chars = lines[i].ToCharArray();
                chars[0] = chars[0] == 'A' ? 'B' : 'A';
                lines[i] = new string(chars);
                break;
            }
        }
        var tampered = string.Join('\n', lines);

        WriteLicenseFile(tampered);

        var result = CreateValidator(ClockAt(2026, 7, 2)).ValidateLicenseFile(_tempDir);

        Assert.Equal(LicenseState.Invalid, result.State);
    }

    /// <summary>
    /// The generated license file should include the human-readable header comments.
    /// </summary>
    [Fact]
    public void GeneratedLicense_HasHumanReadableHeader()
    {
        var content = LicenseFulfillment.LicenseGenerator.Generate(
            "Header Test Dept", "Header Test University", expiryYears: 1, _privateKeyPem);

        Assert.Contains("# TermPoint License", content);
        Assert.Contains("# Department: Header Test Dept", content);
        Assert.Contains("# Institution: Header Test University", content);
        Assert.Contains("# Do not edit below this line.", content);
    }

    private sealed class FixedClock : IClock
    {
        public DateTime UtcNow { get; }
        public FixedClock(DateTime utcNow) => UtcNow = utcNow;
    }
}
