using System.Text;
using TermPoint.Models;

namespace TermPoint.Services;

/// <summary>
/// Generates the next available section code for a given <see cref="SectionCodePattern"/>.
/// </summary>
public static class SectionCodeGenerator
{
    /// <summary>
    /// Maximum number of codes to try before giving up. Prevents unbounded loops when every
    /// code in a long sequence is already taken.
    /// </summary>
    private const int MaxAttempts = 500;

    /// <summary>
    /// Returns the first code in the pattern's sequence that is not already taken,
    /// or <c>null</c> if all codes within <see cref="MaxAttempts"/> are exhausted.
    /// </summary>
    /// <param name="pattern">The pattern defining the code structure and increment rule.</param>
    /// <param name="isCodeTaken">
    /// Predicate returning <c>true</c> when the given code already exists in the target
    /// course/semester. Typically a partial application of
    /// <c>ISectionRepository.ExistsBySectionCode</c>.
    /// </param>
    public static string? GetNextCode(SectionCodePattern pattern, Func<string, bool> isCodeTaken)
    {
        foreach (var candidate in EnumerateCodes(pattern))
        {
            if (!isCodeTaken(candidate))
                return candidate;
        }
        return null;
    }

    /// <summary>
    /// Returns the first few codes in the pattern's sequence for display as a preview.
    /// Used by the admin editor to verify the pattern looks correct before saving.
    /// </summary>
    /// <param name="pattern">The pattern to preview.</param>
    /// <param name="count">Number of example codes to return (default 3).</param>
    public static IReadOnlyList<string> GetPreviewCodes(SectionCodePattern pattern, int count = 3)
    {
        return EnumerateCodes(pattern).Take(count).ToList();
    }

    /// <summary>
    /// Returns <c>true</c> when <paramref name="code"/> could have been generated by
    /// <paramref name="pattern"/> — i.e. it matches the prefix/suffix and its incrementing
    /// part is reachable from the pattern's starting value.
    /// </summary>
    /// <param name="code">The section code to test (case-sensitive).</param>
    /// <param name="pattern">The pattern to match against.</param>
    public static bool MatchesPattern(string code, SectionCodePattern pattern)
    {
        var prefix = pattern.Prefix ?? string.Empty;
        var suffix = pattern.Suffix ?? string.Empty;

        if (!code.StartsWith(prefix, StringComparison.Ordinal)) return false;
        if (!code.EndsWith(suffix, StringComparison.Ordinal)) return false;

        int middleLength = code.Length - prefix.Length - suffix.Length;
        if (middleLength <= 0) return false;
        var middle = code.Substring(prefix.Length, middleLength);

        if (pattern.UseLetters)
        {
            // Incrementing part is one or more uppercase letters in lexicographic order
            // (A..Z, AA, AB, ...). It must be at or after the pattern's first letter.
            long? ordinal = LettersToOrdinal(middle);
            long? first   = LettersToOrdinal(pattern.FirstLetter.ToString());
            return ordinal is not null && first is not null && ordinal.Value >= first.Value;
        }
        else
        {
            if (!long.TryParse(middle, out long value)) return false;
            if (value < (long)pattern.FirstNumber) return false;

            long diff = value - (long)pattern.FirstNumber;
            if (diff % pattern.Increment != 0) return false;

            // Verify the string representation matches exactly — distinguishes padded from
            // non-padded patterns (e.g. PadWidth=3 generates "001" not "1").
            string expected = pattern.PadWidth > 0
                ? value.ToString().PadLeft(pattern.PadWidth, '0')
                : value.ToString();
            return middle == expected;
        }
    }

    /// <summary>
    /// Lazily enumerates all codes in the sequence up to <see cref="MaxAttempts"/>.
    /// </summary>
    private static IEnumerable<string> EnumerateCodes(SectionCodePattern pattern)
    {
        if (pattern.UseLetters)
        {
            // Lexicographic / Excel-column sequence starting at FirstLetter:
            // A, B, ... Z, AA, AB, ... AZ, BA, ... Bounded only by MaxAttempts.
            long start = LettersToOrdinal(pattern.FirstLetter.ToString()) ?? 1;
            for (int i = 0; i < MaxAttempts; i++)
            {
                yield return $"{pattern.Prefix}{OrdinalToLetters(start + i)}{pattern.Suffix}";
            }
        }
        else
        {
            for (int i = 0; i < MaxAttempts; i++)
            {
                long value = (long)pattern.FirstNumber + (long)pattern.Increment * i;
                string numStr = pattern.PadWidth > 0
                    ? value.ToString().PadLeft(pattern.PadWidth, '0')
                    : value.ToString();
                yield return $"{pattern.Prefix}{numStr}{pattern.Suffix}";
            }
        }
    }

    /// <summary>
    /// Converts an all-uppercase letter string to its 1-indexed position in the
    /// lexicographic letter sequence (bijective base-26): A=1, ... Z=26, AA=27, AB=28, ...
    /// </summary>
    /// <param name="letters">The letter string to convert.</param>
    /// <returns>
    /// The 1-indexed position, or <c>null</c> if <paramref name="letters"/> is empty or
    /// contains any character outside <c>A</c>–<c>Z</c> (case-sensitive).
    /// </returns>
    private static long? LettersToOrdinal(string letters)
    {
        if (string.IsNullOrEmpty(letters)) return null;

        long value = 0;
        foreach (char c in letters)
        {
            if (c < 'A' || c > 'Z') return null;
            value = value * 26 + (c - 'A' + 1);
        }
        return value;
    }

    /// <summary>
    /// Inverse of <see cref="LettersToOrdinal"/>: converts a 1-indexed position back to its
    /// letter string (1 → "A", 26 → "Z", 27 → "AA", 28 → "AB", ...).
    /// </summary>
    /// <param name="ordinal">A 1-indexed position; assumed to be &gt;= 1.</param>
    private static string OrdinalToLetters(long ordinal)
    {
        var sb = new StringBuilder();
        while (ordinal > 0)
        {
            ordinal--;                                    // shift to 0-indexed for the modulo
            sb.Insert(0, (char)('A' + ordinal % 26));
            ordinal /= 26;
        }
        return sb.ToString();
    }
}
