// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>Section code prefixes used to auto-generate section codes.</summary>
    public static readonly IReadOnlyList<SectionPrefix> SectionPrefixes =
    [
        new SectionPrefix { Id = "3c746927-dab3-444c-8b26-42837ad9fc17", Prefix = "A#", CampusId = "080e1213-6a8a-412c-a128-1d96c6b77a20" },
        new SectionPrefix { Id = "c225bfbd-19a7-4e8c-8a74-95ff4b6d701d", Prefix = "AB", CampusId = "080e1213-6a8a-412c-a128-1d96c6b77a20" },
        new SectionPrefix { Id = "6688b751-7df0-4b3e-b013-287fd3ebc707", Prefix = "C#", CampusId = "428a7a21-4a46-43fc-bba7-f1d29149e447" },
        new SectionPrefix { Id = "05ab5136-5873-4de8-b695-934e36d50796", Prefix = "CH", CampusId = "428a7a21-4a46-43fc-bba7-f1d29149e447" },
    ];
}
