// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>All courses offered in the demo academic year.</summary>
    public static readonly IReadOnlyList<Course> Courses =
    [
        new Course
        {
            Id           = "9dadd75d-f186-4418-be15-23abe5154bc1",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH101",
            Title        = "",
            Level        = "100",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "6ce8fede-52d2-42bc-92a6-e0ec091a3a3a",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH105",
            Title        = "Mathematics for Elementary Teachers",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422"],
        },
        new Course
        {
            Id           = "c1eade4e-ea4a-4a48-990f-1ee7294ba48e",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH110",
            Title        = "Pre-calculus Mathematics",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422"],
        },
        new Course
        {
            Id           = "9bdb469e-c3de-4bc8-99dc-4630d1e7fbfe",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH111",
            Title        = "Calculus I",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "f7741a59-9e22-4225-bc10-ea3f986f58a2",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH112",
            Title        = "Calculus II",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "2aab3798-a79d-4182-8a14-a38eb34f8aed",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH118",
            Title        = "Calculus II for Life Sciences",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "cf33c755-4bf9-493c-a50a-649131016e2c",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH123",
            Title        = "Everyday Math and Stats",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "478b8606-073e-42c1-9fb6-3816ba36a8d3",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH125",
            Title        = "Introduction to Discrete Math",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "174c3b18-e1ee-43b6-946d-96845c762f7e", "8ac669a3-aa14-475a-b8df-99287e37ab26"],
        },
        new Course
        {
            Id           = "bedde79f-c22c-4275-9c81-4683fa992868",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH140",
            Title        = "Algebra and Functions for Business",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "c1599663-f498-4459-9cb0-26d76986eaa2"],
        },
        new Course
        {
            Id           = "f79bf456-99be-425f-94e4-7806dc6abb2f",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH141",
            Title        = "Calculus for Business",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "c1599663-f498-4459-9cb0-26d76986eaa2"],
        },
        new Course
        {
            Id           = "071ec762-b388-46d2-8145-cd009a5ea507",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH152",
            Title        = "Linear Algebra for Engineering",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "292f0de1-cdc8-458a-986b-fe647f159d29",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH205",
            Title        = "Mathematics for Elementary School Teachers",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f"],
        },
        new Course
        {
            Id           = "bfae3a44-af0d-4db7-bc0d-ac92016fcb38",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH211",
            Title        = "Calculus III",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "1070a7c1-5547-4387-97e3-cb333a490a8c",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH221",
            Title        = "Linear Algebra",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "87d844f0-669c-41d2-bf17-6feddf692152",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH225",
            Title        = "Topic in Discrete Mathematics",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "8ac669a3-aa14-475a-b8df-99287e37ab26", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "6cff42b2-d3bb-4ba7-93f5-8ebe348c287b",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH255",
            Title        = "Ordinary Differential Equations",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "85590254-3073-4402-9518-7c50376ecd93",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH265",
            Title        = "Transition to Advanced Mathematics",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "942ab760-c4ab-484f-bf34-fa1b24c9340a",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH312",
            Title        = "Vector Calculus",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "1737ddfe-3929-4e32-bce6-afe65bc82ae3",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH316",
            Title        = "Numerical Analysis",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "d9bba9bc-74db-4f61-a441-8940cc4b51b2",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH322",
            Title        = "Complex Variables",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "dfa70abb-1ba1-4ff5-98b2-9c71c5997bea",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH339",
            Title        = "Introduction to Field Theory and Applications",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "dc944383-9369-438e-9845-6a9d1c3e386b",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH340",
            Title        = "Introduction to Analysis",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "dcc15481-cab5-49f9-b6a7-75ab6be29c91",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH343",
            Title        = "Applied Discrete Mathematics",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "ba2b5efb-b14a-4d66-98d4-f8c054e2b5c8",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH345",
            Title        = "Modern Geometries",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "ee4838a8-5667-4cd0-ba42-40005f92146d",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH355",
            Title        = "Number Theory and Applications",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "9b0bae93-8abf-4073-9a00-a8e0fdfa2820",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH368",
            Title        = "Operations Research",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "13937de3-50d0-407c-b508-9ab4051c712c",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH370",
            Title        = "Probability and Stochastic Processes",
            Level        = "300",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "d0ff2185-a4b6-4312-ba5d-9c3a74e0f762",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH381",
            Title        = "Mathematical Physics",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "278e63ef-0459-432b-9333-04a43f29659d",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH410",
            Title        = "History of Mathematics ",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da", "15895260-2ba2-4bc0-98e3-481d52880f62"],
        },
        new Course
        {
            Id           = "3c61b1db-740c-4b39-a08c-56dd08e1e9f1",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH416",
            Title        = "Partial Differential Equations",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["15895260-2ba2-4bc0-98e3-481d52880f62", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "4df1193b-69de-4188-b5a4-4fa7ab1d74fc",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH438",
            Title        = "Advanced Linear Algebra",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "58f03b92-c4c2-4066-82ad-894053239742",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH439",
            Title        = "Group Theory",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["410e1f32-0d17-4322-a57d-c5297a5742da", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "15895260-2ba2-4bc0-98e3-481d52880f62"],
        },
        new Course
        {
            Id           = "f3977101-96bd-44ec-bca6-913e10b4be13",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH440",
            Title        = "Fourier Analysis",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["410e1f32-0d17-4322-a57d-c5297a5742da", "15895260-2ba2-4bc0-98e3-481d52880f62", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb"],
        },
        new Course
        {
            Id           = "8a34f6ba-3697-45ad-b7d2-67d37486a01f",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH444",
            Title        = "Metric Spaces",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "ab5ce596-126a-41a5-9673-0e61069ea171",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH445",
            Title        = "Introduction to Graph Theory",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "7f901699-d74f-479b-a76f-f5e54e04556a",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH480",
            Title        = "Selected Topics in Mathematics",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["15895260-2ba2-4bc0-98e3-481d52880f62", "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "f0b3d7b9-f7ee-43bb-a908-fcf5742fd585",
            SubjectId    = "7408a213-1408-49c9-af20-2603595f73fd",
            CalendarCode = "MATH498",
            Title        = "Physics upper-level",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "4c911441-03fc-41a8-8ee1-76bd6fbea037",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT104",
            Title        = "Introductory Statistics",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "13560b58-42d7-4643-bea0-d171c7e1134f",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT106",
            Title        = "Statistics I",
            Level        = "100",
            IsActive     = true,
            TagIds       = ["316d9bbb-8af8-4807-a957-ad91995b9422", "c1599663-f498-4459-9cb0-26d76986eaa2", "8ac669a3-aa14-475a-b8df-99287e37ab26", "174c3b18-e1ee-43b6-946d-96845c762f7e"],
        },
        new Course
        {
            Id           = "01ef318e-4d22-4389-b728-47702f685a89",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT270",
            Title        = "Introduction to Probability and Statistics",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "950da112-a83f-4539-892f-66ff1dfadc74", "8ac669a3-aa14-475a-b8df-99287e37ab26"],
        },
        new Course
        {
            Id           = "1435e82a-c2b2-43b5-9fdc-43e420a03e24",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT271",
            Title        = "Introduction to Data Analysis and Statistical Modeling",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55"],
        },
        new Course
        {
            Id           = "a2ecef1b-a91d-4484-b335-f0cba17df381",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT272",
            Title        = "Statistical Graphics and Languages",
            Level        = "200",
            IsActive     = true,
            TagIds       = ["32380fd7-ab94-4b2c-be15-eafc8504914f", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55"],
        },
        new Course
        {
            Id           = "23d2bb1c-6e1e-4fbb-b4dc-53c5d1244f78",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT307",
            Title        = "Data Visualization",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "f0b48e1b-c3dc-4346-8583-6c6961135719",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT315",
            Title        = "Applied Regression Analysis",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["dc1a4f3a-fe81-45fd-a704-6bedac31ca55", "410e1f32-0d17-4322-a57d-c5297a5742da", "bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "8ac669a3-aa14-475a-b8df-99287e37ab26"],
        },
        new Course
        {
            Id           = "f868b329-d5bc-452d-8481-d6d6bf9ec30a",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT330",
            Title        = "Design of Experiments",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "df0ebdc7-9f20-4e48-a014-64b48a5421bc",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT350",
            Title        = "Survey Design and Sampling",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "f99ed3a4-856f-44b9-aa3b-5c3d29fac755",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT370",
            Title        = "Probability and Stochastic Processes",
            Level        = "300",
            IsActive     = true,
            TagIds       = ["bba39e46-ee2c-4d10-8f2f-e415ac18af8e", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "c53ad74e-d2ac-4bc3-90b4-615edc207fe6",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT402",
            Title        = "Applied Generalized Linear Model and Survival Analysis",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "c91fbeff-c22d-4f6a-851a-ad6d5a23dcae",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT430",
            Title        = "Time Series and Forecasting",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["15895260-2ba2-4bc0-98e3-481d52880f62", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "86e2c5d1-393d-4b2f-954b-4e0bf5b1aece",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT431",
            Title        = "Data Mining",
            Level        = "400",
            IsActive     = true,
            TagIds       = ["15895260-2ba2-4bc0-98e3-481d52880f62", "dc1a4f3a-fe81-45fd-a704-6bedac31ca55", "410e1f32-0d17-4322-a57d-c5297a5742da"],
        },
        new Course
        {
            Id           = "dfc9626a-2e3f-461a-872c-3a8c7f682bea",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT470",
            Title        = "Applied Multivariate Statistical Analysis",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
        new Course
        {
            Id           = "b679d4b2-6c0a-4f52-a454-b7658b2e0550",
            SubjectId    = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99",
            CalendarCode = "STAT488",
            Title        = "Special Topics in Statistics",
            Level        = "400",
            IsActive     = true,
            TagIds       = [],
        },
    ];
}
