// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>The single academic year included in the demo.</summary>
    public static readonly AcademicYear AcademicYear = new()
    {
        Id   = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10",
        Name = "2024-2025",
    };
}
