// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>All instructors. Names have been anonymised — real names are not stored here.
    /// IDs are preserved so all section references remain valid.</summary>
    public static readonly IReadOnlyList<Instructor> Instructors =
    [
        new Instructor
        {
            Id          = "cf787df7-6885-491f-a3ff-7ec90d168d11",
            FirstName   = "Arthur",
            LastName    = "York",
            Initials    = "AY",
            Email       = "",
            Notes       = "",
            StaffTypeId = null,
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "7f9e8b8c-d6ce-4099-bcfb-442512c2eb5a",
            FirstName   = "Rachel",
            LastName    = "Ramos",
            Initials    = "RR",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "e8e4f7cc-4b63-413d-af2b-b9e043fba7d5",
            FirstName   = "Fiona",
            LastName    = "Everett",
            Initials    = "FE",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "fa8a3ba9-09fb-405b-a5a0-5f6654937062",
            FirstName   = "Josephine",
            LastName    = "Irving",
            Initials    = "JI",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "d220df63-c99f-4714-a998-a139ff4ece1a",
            FirstName   = "Calvin",
            LastName    = "Burke",
            Initials    = "CB",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2bed8eae-52fe-4758-afe2-80570710dded",
            IsActive    = false,
        },
        new Instructor
        {
            Id          = "e6cd3230-57d9-490e-8af8-f373202b60af",
            FirstName   = "Edmund",
            LastName    = "Daley",
            Initials    = "ED",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "783edccf-a51a-4ed6-bd5d-f1a90e5e52c1",
            FirstName   = "Quinn",
            LastName    = "Quinlan",
            Initials    = "QQ",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "45443775-9f17-4014-9ccf-2883d0f9cd7c",
            FirstName   = "Grace",
            LastName    = "Graham",
            Initials    = "GG",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "1beac5c1-c526-4bfd-8c60-38aab3050049",
            FirstName   = "Clara",
            LastName    = "Chen",
            Initials    = "CC",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "f99517f4-b948-4be6-af84-6077230cd8b5",
            FirstName   = "Ivan",
            LastName    = "Hayward",
            Initials    = "IH",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "9423407a-611a-493b-99e7-0c4598fae47b",
            FirstName   = "Teresa",
            LastName    = "Townsend",
            Initials    = "TT",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "722f4b44-9ffb-466e-afec-6cc5b938cac3",
            FirstName   = "Olivia",
            LastName    = "Obrien",
            Initials    = "OO",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "a82d23dc-ad15-4acb-9856-c6117812bec4",
            FirstName   = "Vivian",
            LastName    = "Vance",
            Initials    = "VV",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "d25cfbc5-427d-41f4-ba80-28e7df271855",
            FirstName   = "Diana",
            LastName    = "Callahan",
            Initials    = "DC",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "6b9196f0-509c-4d91-9048-da80acbb68be",
            FirstName   = "Nathan",
            LastName    = "Nash",
            Initials    = "NN",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "c9139157-4e8a-4362-95ba-17b0acbce3b8",
            FirstName   = "Yasmin",
            LastName    = "Xu",
            Initials    = "YX",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "4fb451c8-859f-4c05-92f2-ac30b9e07bfe",
            FirstName   = "Julian",
            LastName    = "Janssen",
            Initials    = "JJ",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = false,
        },
        new Instructor
        {
            Id          = "a8dec015-c8af-4ea7-8c8f-c3686b6b784c",
            FirstName   = "Walter",
            LastName    = "Warren",
            Initials    = "WW",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "55e7fca0-29f8-485c-a44b-5b02a15f070e",
            FirstName   = "Lawrence",
            LastName    = "Lawson",
            Initials    = "LL",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "5bde3ae8-f1c8-4dbd-832d-f05062eaf33b",
            FirstName   = "Maria",
            LastName    = "Monroe",
            Initials    = "MM",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2bed8eae-52fe-4758-afe2-80570710dded",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "1675dddc-922e-46bb-a44f-938023d5f9d3",
            FirstName   = "Benjamin",
            LastName    = "Brennan",
            Initials    = "BB",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "38a1f82c-20a3-4c6e-8f0d-a1bf3632752d",
            FirstName   = "Franklin",
            LastName    = "Foster",
            Initials    = "FF",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "a7a98ac5-a9b6-4b01-a24d-894a56235f51",
            FirstName   = "Ulrich",
            LastName    = "Underwood",
            Initials    = "UU",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "4f95234f-6f60-44f4-917d-8d68cd17e4fc",
            FirstName   = "Isabel",
            LastName    = "Ingram",
            Initials    = "II",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "f03db981-3a28-409e-8c57-144902725fe9",
            FirstName   = "Harriet",
            LastName    = "Griffith",
            Initials    = "HG",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "2c637f63-2498-4131-b311-887994328885",
            FirstName   = "Elena",
            LastName    = "Ellis",
            Initials    = "EE",
            Email       = "",
            Notes       = "",
            StaffTypeId = null,
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "8cbd5da9-a917-497c-aa4d-75c0ed1aff03",
            FirstName   = "Samuel",
            LastName    = "Sterling",
            Initials    = "SS",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2bed8eae-52fe-4758-afe2-80570710dded",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "d073b8ae-2e41-48f3-a85a-8b30715292bc",
            FirstName   = "Beatrice",
            LastName    = "Aldridge",
            Initials    = "BA",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "0fbeaa40-c2b1-4529-8d7e-5f42ee947770",
            FirstName   = "Alice",
            LastName    = "Abbott",
            Initials    = "AA",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "5510ddba-afb2-4914-afc6-a49d86cfe200",
            FirstName   = "Karen",
            LastName    = "Kelley",
            Initials    = "KK",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = false,
        },
        new Instructor
        {
            Id          = "ec9e1ccf-9601-4c86-85ff-3f62d65689d2",
            FirstName   = "Gerald",
            LastName    = "Flynn",
            Initials    = "GF",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "7602678f-c70c-48fa-8963-21e0ad4626b5",
            FirstName   = "Patrick",
            LastName    = "Pierce",
            Initials    = "PP",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "4b092ef5-78d4-407c-a179-6b24a38c9ef4",
            FirstName   = "Henry",
            LastName    = "Harmon",
            Initials    = "HH",
            Email       = "",
            Notes       = "",
            StaffTypeId = "1ec54415-25fa-4621-a841-ddd615451cd4",
            IsActive    = true,
        },
        new Instructor
        {
            Id          = "23c14ce5-a894-42af-aa48-964d2da4f317",
            FirstName   = "David",
            LastName    = "Donovan",
            Initials    = "DD",
            Email       = "",
            Notes       = "",
            StaffTypeId = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa",
            IsActive    = true,
        },
    ];
}
