// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>Section type property values (e.g. Lecture, Lab, Tutorial).</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> SectionTypes =
    [
        new SectionPropertyValue { Id = "f0a00906-927d-443e-a0f0-674aa12315b6", Name = "F2F (TRD)", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "adf280ce-9ec7-4c07-8ea9-283aac52cfac", Name = "Blend (HYB)", SectionCodeAbbreviation = null, SortOrder = 1 },
        new SectionPropertyValue { Id = "b83cd9d3-d1b2-4a48-ae78-d7de96c93040", Name = "Online Asynch (OLO)", SectionCodeAbbreviation = null, SortOrder = 2 },
        new SectionPropertyValue { Id = "9cb3654a-faef-4d13-85ac-0e4acf2037cc", Name = "Online Synch (OLM)", SectionCodeAbbreviation = null, SortOrder = 3 },
    ];

    /// <summary>Meeting type property values (e.g. In-Person, Online, Hybrid).</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> MeetingTypes =
    [
        new SectionPropertyValue { Id = "46d58ac8-7ec0-4dbe-b8bd-49cddcef02e7", Name = "F2F Lesson", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "f0012b99-f9f4-4af0-8545-d29841ea6d09", Name = "Remote Lesson", SectionCodeAbbreviation = null, SortOrder = 1 },
        new SectionPropertyValue { Id = "0deb04c1-8de8-401a-9098-313b18c11f0f", Name = "Lab", SectionCodeAbbreviation = null, SortOrder = 2 },
    ];

    /// <summary>Staff type property values (e.g. Full-Time, Sessional).</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> StaffTypes =
    [
        new SectionPropertyValue { Id = "2417d221-7a28-49ff-8a1d-9bbebe3c40fa", Name = "Type B", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "2bed8eae-52fe-4758-afe2-80570710dded", Name = "LTA", SectionCodeAbbreviation = null, SortOrder = 1 },
        new SectionPropertyValue { Id = "1ec54415-25fa-4621-a841-ddd615451cd4", Name = "Sess.", SectionCodeAbbreviation = null, SortOrder = 2 },
        new SectionPropertyValue { Id = "d9af02cd-5dfa-4af6-b06a-a6245976a7a1", Name = "Faculty (Permanent)", SectionCodeAbbreviation = null, SortOrder = 3 },
        new SectionPropertyValue { Id = "b38b0744-fa43-443d-a41f-25d35db1fd21", Name = "Staff (Permanent)", SectionCodeAbbreviation = null, SortOrder = 4 },
        new SectionPropertyValue { Id = "8d365c00-5e86-4cc6-87e6-f0979fb6f82c", Name = "Lab Instructor", SectionCodeAbbreviation = null, SortOrder = 5 },
        new SectionPropertyValue { Id = "bafa6df0-43fe-4460-9ac8-f8cb1c644530", Name = "Lab Assistant", SectionCodeAbbreviation = null, SortOrder = 6 },
    ];

    /// <summary>Campus property values.</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> Campuses =
    [
        new SectionPropertyValue { Id = "080e1213-6a8a-412c-a128-1d96c6b77a20", Name = "Abbotsford", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "428a7a21-4a46-43fc-bba7-f1d29149e447", Name = "Chilliwack", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "12e42d9f-1864-4199-8f14-e4cb4d4891f9", Name = "ABB", SectionCodeAbbreviation = null, SortOrder = 2 },
        new SectionPropertyValue { Id = "37843bd1-afec-483b-90a1-2e4708fd8a51", Name = "CHWK", SectionCodeAbbreviation = null, SortOrder = 3 },
    ];

    /// <summary>Tag property values.</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> Tags =
    [
        new SectionPropertyValue { Id = "316d9bbb-8af8-4807-a957-ad91995b9422", Name = "1st Yr", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "32380fd7-ab94-4b2c-be15-eafc8504914f", Name = "2nd Yr", SectionCodeAbbreviation = null, SortOrder = 1 },
        new SectionPropertyValue { Id = "bba39e46-ee2c-4d10-8f2f-e415ac18af8e", Name = "3rd Yr", SectionCodeAbbreviation = null, SortOrder = 2 },
        new SectionPropertyValue { Id = "15895260-2ba2-4bc0-98e3-481d52880f62", Name = "4th Yr", SectionCodeAbbreviation = null, SortOrder = 3 },
        new SectionPropertyValue { Id = "410e1f32-0d17-4322-a57d-c5297a5742da", Name = "Upper level", SectionCodeAbbreviation = null, SortOrder = 4 },
        new SectionPropertyValue { Id = "dc1a4f3a-fe81-45fd-a704-6bedac31ca55", Name = "DAC", SectionCodeAbbreviation = null, SortOrder = 5 },
        new SectionPropertyValue { Id = "56e32452-4b22-4ddc-8d4f-94d0c61f8ffb", Name = "BSc Math", SectionCodeAbbreviation = null, SortOrder = 6 },
        new SectionPropertyValue { Id = "c1599663-f498-4459-9cb0-26d76986eaa2", Name = "Bus. Service", SectionCodeAbbreviation = null, SortOrder = 7 },
        new SectionPropertyValue { Id = "174c3b18-e1ee-43b6-946d-96845c762f7e", Name = "Service", SectionCodeAbbreviation = null, SortOrder = 8 },
        new SectionPropertyValue { Id = "950da112-a83f-4539-892f-66ff1dfadc74", Name = "Cross-listed", SectionCodeAbbreviation = null, SortOrder = 9 },
        new SectionPropertyValue { Id = "85005763-2e4c-4621-8923-5d249e6f5fdd", Name = "ETP", SectionCodeAbbreviation = null, SortOrder = 10 },
        new SectionPropertyValue { Id = "8033ae32-11ea-433d-ba01-3312a790a2a0", Name = "PHYS", SectionCodeAbbreviation = null, SortOrder = 11 },
        new SectionPropertyValue { Id = "5bed326b-1538-4fd6-bc67-c9cb6643fa26", Name = "Bus PBD", SectionCodeAbbreviation = null, SortOrder = 12 },
        new SectionPropertyValue { Id = "8ac669a3-aa14-475a-b8df-99287e37ab26", Name = "CompSci", SectionCodeAbbreviation = null, SortOrder = 13 },
        new SectionPropertyValue { Id = "70e3f353-09f9-46f6-8ba6-66a7c0b11ca3", Name = "Comp", SectionCodeAbbreviation = null, SortOrder = 14 },
    ];

    /// <summary>Resource property values.</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> Resources =
    [
        new SectionPropertyValue { Id = "66a057fb-9bdd-4697-ba96-68d9d6369dbe", Name = "e.g. Laptop cart", SectionCodeAbbreviation = null, SortOrder = 0 },
    ];

    /// <summary>Reserve property values.</summary>
    public static readonly IReadOnlyList<SectionPropertyValue> Reserves =
    [
        new SectionPropertyValue { Id = "0098b79d-9110-470a-91c4-c75ca8d535c5", Name = "MAJ BIO", SectionCodeAbbreviation = null, SortOrder = 0 },
        new SectionPropertyValue { Id = "dd9548a9-89a8-4e47-9b27-787474da69cc", Name = "MAJ ENSX", SectionCodeAbbreviation = null, SortOrder = 1 },
        new SectionPropertyValue { Id = "1b4d6507-2d1f-48ca-82b0-e3285f468bae", Name = "ATT INRS", SectionCodeAbbreviation = null, SortOrder = 2 },
        new SectionPropertyValue { Id = "10d7be1f-53c7-49e5-b716-db44e00582e1", Name = "MAJ ECON", SectionCodeAbbreviation = null, SortOrder = 3 },
        new SectionPropertyValue { Id = "cf226456-991e-43cd-8041-bfc9fa71b82d", Name = "MAJ DACX", SectionCodeAbbreviation = null, SortOrder = 4 },
        new SectionPropertyValue { Id = "74687792-dde8-40fb-b74b-c9deecf44e1d", Name = "PROG BSc", SectionCodeAbbreviation = null, SortOrder = 5 },
        new SectionPropertyValue { Id = "49337096-ae7c-4f4c-898e-d4294e4686e2", Name = "DEPT COMP", SectionCodeAbbreviation = null, SortOrder = 6 },
        new SectionPropertyValue { Id = "bfddf492-6d29-4a7e-87f6-84ca7b3d3c5d", Name = "Fos ENPH", SectionCodeAbbreviation = null, SortOrder = 7 },
        new SectionPropertyValue { Id = "e9334110-3e6e-479d-abfc-de1572c681ac", Name = "DEPT BUS", SectionCodeAbbreviation = null, SortOrder = 8 },
        new SectionPropertyValue { Id = "65bf217b-6ec6-4dd6-b8bd-85a8bbe7246f", Name = "MECH ENG", SectionCodeAbbreviation = null, SortOrder = 9 },
        new SectionPropertyValue { Id = "d96d28aa-1cef-4f73-841e-ad4f193d64d1", Name = "BUS AN PUB", SectionCodeAbbreviation = null, SortOrder = 10 },
    ];

    /// <summary>
    /// All section property values across all types, combined into a single list.
    /// Used by repositories that need to resolve any property value by ID.
    /// </summary>
    public static IReadOnlyList<SectionPropertyValue> AllSectionProperties =>
        [.. SectionTypes, .. MeetingTypes, .. StaffTypes, .. Campuses, .. Tags, .. Resources, .. Reserves];
}
