// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>All semesters in the demo academic year.</summary>
    public static readonly IReadOnlyList<Semester> Semesters =
    [
        new Semester { Id = "0691bc17-4485-439f-8f15-216bb840923b", AcademicYearId = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10", Name = "Fall", SortOrder = 0 },
        new Semester { Id = "e57bb43e-7c24-46b0-8142-89d1f526d652", AcademicYearId = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10", Name = "Winter", SortOrder = 1 },
        new Semester { Id = "50b9f773-32f9-4003-a7c0-8a4644c254d2", AcademicYearId = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10", Name = "Early Summer", SortOrder = 2 },
        new Semester { Id = "1dd28fc7-fa03-4a67-876f-bcb41e52a104", AcademicYearId = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10", Name = "Summer", SortOrder = 3 },
        new Semester { Id = "d24bab7b-eefc-4093-b576-1ea7a95a2a04", AcademicYearId = "51fcc7a4-5a22-4f3b-9d70-62be62bafe10", Name = "Late Summer", SortOrder = 4 },
    ];
}
