// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>All rooms referenced by sections in the demo academic year.</summary>
    public static readonly IReadOnlyList<Room> Rooms =
    [
        new Room
        {
            Id         = "fee765c6-9eaf-4260-97ce-cf3d8d508fa1",
            Building   = "",
            RoomNumber = "D219",
            Capacity   = 0,
            Features   = "",
            Notes      = "",
            SortOrder  = 0,
        },
    ];
}
