// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>Legal section start times for the demo academic year, keyed by block length in hours.
    /// Used by the section editor to populate the start-time picker.</summary>
    public static readonly IReadOnlyList<LegalStartTime> LegalStartTimes =
    [
        new LegalStartTime { BlockLength = 1.5, StartTimes = [510, 600, 690, 780, 870, 960, 1050, 1080] },
        new LegalStartTime { BlockLength = 2, StartTimes = [510, 540, 630, 780, 900, 1050, 1080, 1170, 1200] },
        new LegalStartTime { BlockLength = 3, StartTimes = [510, 690, 870, 960, 1050, 1080, 1110, 1140] },
        new LegalStartTime { BlockLength = 4, StartTimes = [510, 780, 1050, 1080] },
    ];
}
