// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>Named day patterns used in the section schedule editor (e.g. MWF, TTh).</summary>
    public static readonly IReadOnlyList<BlockPattern> BlockPatterns =
    [
    ];
}
