// <auto-generated>
//   This file was generated by DemoDataGenerator.
//   To refresh: open the source database in debug mode → Debug flyout → Generate Demo Data.
//   DO NOT edit this file manually — changes will be overwritten on the next generation.
// </auto-generated>

using SchedulingAssistant.Models;

namespace SchedulingAssistant.Demo;

public static partial class DemoData
{
    /// <summary>All subjects (academic departments / disciplines) in the demo data.</summary>
    public static readonly IReadOnlyList<Subject> Subjects =
    [
        new Subject { Id = "7408a213-1408-49c9-af20-2603595f73fd", Name = "Mathematics", CalendarAbbreviation = "MATH" },
        new Subject { Id = "77ecb1e7-d6a7-4e39-896c-6f2def02ec99", Name = "Statistics", CalendarAbbreviation = "STAT" },
    ];
}
