using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SchedulingAssistant.Data.Repositories;
using SchedulingAssistant.Models;
using SchedulingAssistant.Services;
using SchedulingAssistant.ViewModels.GridView;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SchedulingAssistant.ViewModels.Management;

public partial class SectionListViewModel : ViewModelBase
{
    private readonly SectionRepository _sectionRepo;
    private readonly CourseRepository _courseRepo;
    private readonly InstructorRepository _instructorRepo;
    private readonly RoomRepository _roomRepo;
    private readonly LegalStartTimeRepository _legalStartTimeRepo;
    private readonly SemesterContext _semesterContext;
    private readonly ScheduleGridViewModel _scheduleGridVm;
    private readonly SectionPropertyRepository _propertyRepo;

    [ObservableProperty] private ObservableCollection<SectionListItemViewModel> _sectionItems = new();
    [ObservableProperty] private SectionListItemViewModel? _selectedItem;
    [ObservableProperty] private SectionListItemViewModel? _expandedItem;
    [ObservableProperty] private SectionEditViewModel? _editVm;

    /// <summary>True when an inline editor is open (Add or Edit mode).</summary>
    public bool IsEditing => EditVm is not null;

    // Raise IsEditing whenever EditVm changes (generated by [ObservableProperty])
    partial void OnEditVmChanged(SectionEditViewModel? value) => OnPropertyChanged(nameof(IsEditing));

    public Section? SelectedSection => SelectedItem?.Section;

    /// <summary>Set by the view code-behind to display error messages.</summary>
    public Func<string, Task>? ShowError { get; set; }

    public SectionListViewModel(
        SectionRepository sectionRepo,
        CourseRepository courseRepo,
        InstructorRepository instructorRepo,
        RoomRepository roomRepo,
        LegalStartTimeRepository legalStartTimeRepo,
        SemesterContext semesterContext,
        ScheduleGridViewModel scheduleGridVm,
        SectionPropertyRepository propertyRepo)
    {
        _sectionRepo = sectionRepo;
        _courseRepo = courseRepo;
        _instructorRepo = instructorRepo;
        _roomRepo = roomRepo;
        _legalStartTimeRepo = legalStartTimeRepo;
        _semesterContext = semesterContext;
        _scheduleGridVm = scheduleGridVm;
        _propertyRepo = propertyRepo;

        _semesterContext.PropertyChanged += OnSemesterContextChanged;

        Load();
    }

    private void OnSemesterContextChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(SemesterContext.SelectedSemesterDisplay))
            Load();
    }

    private void Load()
    {
        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) { SectionItems = new(); return; }

        var courseLookup     = _courseRepo.GetAll().ToDictionary(c => c.Id);
        var instructorLookup = _instructorRepo.GetAll().ToDictionary(i => i.Id);
        var roomLookup       = _roomRepo.GetAll().ToDictionary(r => r.Id);

        // Fetch all property lookups once per load for collapsed card display
        var sectionTypeLookup = _propertyRepo.GetAll(SectionPropertyTypes.SectionType).ToDictionary(v => v.Id);
        var campusLookup      = _propertyRepo.GetAll(SectionPropertyTypes.Campus).ToDictionary(v => v.Id);
        var tagLookup         = _propertyRepo.GetAll(SectionPropertyTypes.Tag).ToDictionary(v => v.Id);
        var resourceLookup    = _propertyRepo.GetAll(SectionPropertyTypes.Resource).ToDictionary(v => v.Id);
        var reserveLookup     = _propertyRepo.GetAll(SectionPropertyTypes.Reserve).ToDictionary(v => v.Id);

        var sections = _sectionRepo.GetAll(semester.Id);
        SectionItems = new ObservableCollection<SectionListItemViewModel>(
            sections.Select(s => new SectionListItemViewModel(
                s, courseLookup, instructorLookup, roomLookup,
                sectionTypeLookup, campusLookup,
                tagLookup, resourceLookup, reserveLookup)));
    }

    [RelayCommand]
    private void Add()
    {
        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) return;
        var section = new Section { SemesterId = semester.Id };
        OpenEdit(section, isNew: true, listItem: null);
    }

    [RelayCommand]
    private void Edit()
    {
        if (SelectedItem is null) return;
        OpenEdit(CloneSection(SelectedItem.Section), isNew: false, listItem: SelectedItem);
    }

    /// <summary>Called from the view when a list item is double-tapped.</summary>
    public void EditItem(SectionListItemViewModel item)
    {
        SelectedItem = item;

        // Guard: if this item is already open, do nothing.
        //
        // Without this, double-tapping the summary card of an already-open section calls
        // OpenEdit again on the same item. OpenEdit creates a fresh SectionEditViewModel
        // and assigns it to EditVm, which causes the ContentControl to tear down and
        // rebuild its visual tree. During that rebuild Avalonia sets ItemsSource on the
        // single-select ComboBoxes (SectionTypes, Campuses, etc.), but their SelectedValue
        // binding resolves before the items finish populating, so the selection appears
        // blank. A second double-tap repeats the cycle and by coincidence resolves in the
        // correct order — making it look like a toggle. Skipping the rebuild when the item
        // is already expanded eliminates the race entirely.
        if (ExpandedItem == item) return;

        OpenEdit(CloneSection(item.Section), isNew: false, listItem: item);
    }

    private void OpenEdit(Section section, bool isNew, SectionListItemViewModel? listItem)
    {
        // Collapse any currently open editor
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;

        var courses         = _courseRepo.GetAllActive();
        var instructors     = _instructorRepo.GetAll();
        var rooms           = _roomRepo.GetAll();
        var legalStartTimes = _legalStartTimeRepo.GetAll();
        var settings        = AppSettings.Load();
        var includeSaturday = settings.IncludeSaturday;

        var sectionTypes  = _propertyRepo.GetAll(SectionPropertyTypes.SectionType);
        var meetingTypes  = _propertyRepo.GetAll(SectionPropertyTypes.MeetingType);
        var campuses      = _propertyRepo.GetAll(SectionPropertyTypes.Campus);
        var allTags       = _propertyRepo.GetAll(SectionPropertyTypes.Tag);
        var allResources  = _propertyRepo.GetAll(SectionPropertyTypes.Resource);
        var allReserves   = _propertyRepo.GetAll(SectionPropertyTypes.Reserve);

        var semesterId = _semesterContext.SelectedSemesterDisplay!.Semester.Id;
        var editVm = new SectionEditViewModel(
            section, isNew,
            courses, instructors, rooms, legalStartTimes, includeSaturday,
            sectionTypes, meetingTypes, campuses,
            allTags, allResources, allReserves,
            isSectionCodeDuplicate: (courseId, code) =>
                _sectionRepo.ExistsBySectionCode(semesterId, courseId, code, isNew ? null : section.Id),
            onSave: s =>
            {
                if (isNew) _sectionRepo.Insert(s); else _sectionRepo.Update(s);
                CollapseEditor();
                Load();
                _scheduleGridVm.Reload();
            },
            defaultBlockLength: settings.PreferredBlockLength);
        editVm.RequestClose = CollapseEditor;
        ExpandedItem = listItem;
        if (listItem is not null) listItem.IsExpanded = true;
        EditVm = editVm;
    }

    [RelayCommand]
    private async Task Copy()
    {
        if (SelectedItem is null) return;
        var source = SelectedItem.Section;

        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) return;

        // Derive a candidate section code by incrementing the trailing integer suffix, if any.
        string? newCode = null;
        if (!string.IsNullOrEmpty(source.CourseId))
        {
            var match = Regex.Match(source.SectionCode, @"^(.*?)(\d+)$");
            if (match.Success)
            {
                var prefix = match.Groups[1].Value;
                var number = int.Parse(match.Groups[2].Value);
                var candidate = $"{prefix}{number + 1}";
                if (!_sectionRepo.ExistsBySectionCode(semester.Id, source.CourseId, candidate, excludeId: null))
                    newCode = candidate;
                else
                    await (ShowError?.Invoke(
                        $"Could not auto-assign a section code: \"{candidate}\" already exists for this course. " +
                        "The section code has been left blank — please enter one before saving.") ?? Task.CompletedTask);
            }
        }

        var newSection = new Section
        {
            SemesterId = semester.Id,
            CourseId   = source.CourseId,
            SectionCode = newCode ?? string.Empty,
        };

        // Insert the new section immediately after the selected one in the list.
        // We open the editor without pre-inserting — the editor's onSave will insert it.
        // But we need it to appear *below* the selected item, so we insert a placeholder
        // list item first, then open the editor on it.
        OpenCopy(newSection, afterItem: SelectedItem);
    }

    private void OpenCopy(Section section, SectionListItemViewModel afterItem)
    {
        // Collapse any currently open editor
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;

        var courses         = _courseRepo.GetAllActive();
        var instructors     = _instructorRepo.GetAll();
        var rooms           = _roomRepo.GetAll();
        var legalStartTimes = _legalStartTimeRepo.GetAll();
        var settings        = AppSettings.Load();
        var includeSaturday = settings.IncludeSaturday;

        var sectionTypes  = _propertyRepo.GetAll(SectionPropertyTypes.SectionType);
        var meetingTypes  = _propertyRepo.GetAll(SectionPropertyTypes.MeetingType);
        var campuses      = _propertyRepo.GetAll(SectionPropertyTypes.Campus);
        var allTags       = _propertyRepo.GetAll(SectionPropertyTypes.Tag);
        var allResources  = _propertyRepo.GetAll(SectionPropertyTypes.Resource);
        var allReserves   = _propertyRepo.GetAll(SectionPropertyTypes.Reserve);

        // Build a minimal placeholder list item so the editor can expand inline.
        var courseLookup     = _courseRepo.GetAll().ToDictionary(c => c.Id);
        var instructorLookup = _instructorRepo.GetAll().ToDictionary(i => i.Id);
        var roomLookup       = _roomRepo.GetAll().ToDictionary(r => r.Id);
        var sectionTypeLookup = _propertyRepo.GetAll(SectionPropertyTypes.SectionType).ToDictionary(v => v.Id);
        var campusLookup      = _propertyRepo.GetAll(SectionPropertyTypes.Campus).ToDictionary(v => v.Id);
        var tagLookup         = _propertyRepo.GetAll(SectionPropertyTypes.Tag).ToDictionary(v => v.Id);
        var resourceLookup    = _propertyRepo.GetAll(SectionPropertyTypes.Resource).ToDictionary(v => v.Id);
        var reserveLookup     = _propertyRepo.GetAll(SectionPropertyTypes.Reserve).ToDictionary(v => v.Id);

        var placeholder = new SectionListItemViewModel(
            section, courseLookup, instructorLookup, roomLookup,
            sectionTypeLookup, campusLookup, tagLookup, resourceLookup, reserveLookup);

        // Insert immediately after the source item
        int insertIndex = SectionItems.IndexOf(afterItem) + 1;
        SectionItems.Insert(insertIndex, placeholder);

        var semesterId = _semesterContext.SelectedSemesterDisplay!.Semester.Id;
        var editVm = new SectionEditViewModel(
            section, isNew: true,
            courses, instructors, rooms, legalStartTimes, includeSaturday,
            sectionTypes, meetingTypes, campuses,
            allTags, allResources, allReserves,
            isSectionCodeDuplicate: (courseId, code) =>
                _sectionRepo.ExistsBySectionCode(semesterId, courseId, code, excludeId: null),
            onSave: s =>
            {
                _sectionRepo.Insert(s);
                CollapseEditor();
                Load();
                _scheduleGridVm.Reload();
            },
            defaultBlockLength: settings.PreferredBlockLength);
        editVm.RequestClose = () =>
        {
            // If cancelled, remove the placeholder row
            SectionItems.Remove(placeholder);
            CollapseEditor();
        };

        ExpandedItem = placeholder;
        placeholder.IsExpanded = true;
        EditVm = editVm;
    }

    [RelayCommand]
    private void Delete()
    {
        if (SelectedSection is null) return;
        if (ExpandedItem?.Section.Id == SelectedSection.Id)
            CollapseEditor();
        _sectionRepo.Delete(SelectedSection.Id);
        Load();
        _scheduleGridVm.Reload();
    }

    private void CollapseEditor()
    {
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;
        ExpandedItem = null;
        EditVm = null;
    }

    private static Section CloneSection(Section s) => new()
    {
        Id              = s.Id,
        SemesterId      = s.SemesterId,
        CourseId        = s.CourseId,
        InstructorAssignments = s.InstructorAssignments
            .Select(a => new InstructorAssignment { InstructorId = a.InstructorId, Workload = a.Workload })
            .ToList(),
        SectionCode     = s.SectionCode,
        Notes           = s.Notes,
        Schedule        = s.Schedule.Select(d => new SectionDaySchedule
        {
            Day             = d.Day,
            StartMinutes    = d.StartMinutes,
            DurationMinutes = d.DurationMinutes,
            MeetingTypeId   = d.MeetingTypeId,
            RoomId          = d.RoomId,
        }).ToList(),
        SectionTypeId   = s.SectionTypeId,
        CampusId        = s.CampusId,
        TagIds          = new List<string>(s.TagIds),
        ResourceIds     = new List<string>(s.ResourceIds),
        Reserves        = s.Reserves.Select(r => new SectionReserve
            { ReserveId = r.ReserveId, Code = r.Code }).ToList(),
    };
}
