using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using SchedulingAssistant.Data.Repositories;
using SchedulingAssistant.Models;
using SchedulingAssistant.Services;
using SchedulingAssistant.ViewModels.GridView;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace SchedulingAssistant.ViewModels.Management;

public partial class SectionListViewModel : ViewModelBase
{
    private readonly SectionRepository _sectionRepo;
    private readonly CourseRepository _courseRepo;
    private readonly InstructorRepository _instructorRepo;
    private readonly RoomRepository _roomRepo;
    private readonly LegalStartTimeRepository _legalStartTimeRepo;
    private readonly BlockPatternRepository _blockPatternRepo;
    private readonly SemesterContext _semesterContext;
    private readonly ScheduleGridViewModel _scheduleGridVm;
    private readonly SectionPropertyRepository _propertyRepo;

    [ObservableProperty] private ObservableCollection<SectionListItemViewModel> _sectionItems = new();
    [ObservableProperty] private SectionListItemViewModel? _selectedItem;
    [ObservableProperty] private SectionListItemViewModel? _expandedItem;
    [ObservableProperty] private SectionEditViewModel? _editVm;
    [ObservableProperty] private string? _lastErrorMessage;

    /// <summary>
    /// Index of the most recently selected item.  Captured whenever SelectedItem
    /// changes to a non-null value so that "Add" can insert after it even if
    /// clicking the header button clears the ListBox selection first.
    /// </summary>
    private int _lastSelectedIndex = -1;
    private bool _suppressSelectionSync = false;

    /// <summary>True when an inline editor is open (Add or Edit mode).</summary>
    public bool IsEditing => EditVm is not null;

    // Raise IsEditing whenever EditVm changes (generated by [ObservableProperty])
    partial void OnEditVmChanged(SectionEditViewModel? value) => OnPropertyChanged(nameof(IsEditing));

    partial void OnSelectedItemChanged(SectionListItemViewModel? value)
    {
        if (value is not null)
            _lastSelectedIndex = SectionItems.IndexOf(value);

        // Push selection to the grid (suppress to avoid echo back)
        if (!_suppressSelectionSync)
        {
            _suppressSelectionSync = true;
            _scheduleGridVm.SelectedSectionId = value?.Section.Id;
            _suppressSelectionSync = false;
        }
    }

    public Section? SelectedSection => SelectedItem?.Section;

    /// <summary>Set by the view code-behind to display error messages.</summary>
    public Func<string, Task>? ShowError { get; set; }

    [RelayCommand]
    public void DismissError() => LastErrorMessage = null;

#if DEBUG
    /// <summary>
    /// DEV ONLY — forces a load failure so the error banner can be tested visually.
    /// Remove before shipping.
    /// </summary>
    [RelayCommand]
    public void SimulateLoadError()
    {
        App.Logger.LogError(new InvalidOperationException("Simulated section list load error"), "SimulateLoadError");
        SectionItems = new();
        LastErrorMessage = "An error occurred loading the section list. See logs for details.";
    }
#endif

    public SectionListViewModel(
        SectionRepository sectionRepo,
        CourseRepository courseRepo,
        InstructorRepository instructorRepo,
        RoomRepository roomRepo,
        LegalStartTimeRepository legalStartTimeRepo,
        BlockPatternRepository blockPatternRepo,
        SemesterContext semesterContext,
        ScheduleGridViewModel scheduleGridVm,
        SectionPropertyRepository propertyRepo)
    {
        _sectionRepo = sectionRepo;
        _courseRepo = courseRepo;
        _instructorRepo = instructorRepo;
        _roomRepo = roomRepo;
        _legalStartTimeRepo = legalStartTimeRepo;
        _blockPatternRepo = blockPatternRepo;
        _semesterContext = semesterContext;
        _scheduleGridVm = scheduleGridVm;
        _propertyRepo = propertyRepo;

        _semesterContext.PropertyChanged += OnSemesterContextChanged;
        _scheduleGridVm.PropertyChanged += OnGridVmPropertyChanged;
        _scheduleGridVm.EditRequested = EditSectionById;

        Load();
    }

    private void OnSemesterContextChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(SemesterContext.SelectedSemesterDisplay))
            Load();
    }

    private void OnGridVmPropertyChanged(object? sender, PropertyChangedEventArgs e)
    {
        if (e.PropertyName != nameof(ScheduleGridViewModel.SelectedSectionId)) return;
        if (_suppressSelectionSync) return;

        var id = _scheduleGridVm.SelectedSectionId;
        if (id == SelectedItem?.Section.Id) return;

        _suppressSelectionSync = true;
        SelectedItem = id is null ? null : SectionItems.FirstOrDefault(i => i.Section.Id == id);
        _suppressSelectionSync = false;
    }

    /// <summary>
    /// Reloads the section list from the database.  When <paramref name="selectSectionId"/>
    /// is supplied the item with that section ID is selected after the list is rebuilt,
    /// so the user can immediately see where the saved section landed.
    /// </summary>
    private void Load(string? selectSectionId = null)
    {
        try
        {
            LoadCore(selectSectionId);
            LastErrorMessage = null;
        }
        catch (Exception ex)
        {
            App.Logger.LogError(ex, "SectionListViewModel.Load");
            SectionItems = new();
            LastErrorMessage = "An error occurred loading the section list. See logs for details.";
        }
    }

    private void LoadCore(string? selectSectionId)
    {
        _lastSelectedIndex = -1;

        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) { SectionItems = new(); return; }

        var courseLookup     = _courseRepo.GetAll().ToDictionary(c => c.Id);
        var instructorLookup = _instructorRepo.GetAll().ToDictionary(i => i.Id);
        var roomLookup       = _roomRepo.GetAll().ToDictionary(r => r.Id);

        // Fetch all property lookups once per load for collapsed card display
        var sectionTypeLookup = _propertyRepo.GetAll(SectionPropertyTypes.SectionType).ToDictionary(v => v.Id);
        var campusLookup      = _propertyRepo.GetAll(SectionPropertyTypes.Campus).ToDictionary(v => v.Id);
        var tagLookup         = _propertyRepo.GetAll(SectionPropertyTypes.Tag).ToDictionary(v => v.Id);
        var resourceLookup    = _propertyRepo.GetAll(SectionPropertyTypes.Resource).ToDictionary(v => v.Id);
        var reserveLookup     = _propertyRepo.GetAll(SectionPropertyTypes.Reserve).ToDictionary(v => v.Id);

        // Snapshot collapsed state so it survives the rebuild
        var collapsedIds = SectionItems
            .Where(i => i.IsCollapsed)
            .Select(i => i.Section.Id)
            .ToHashSet();

        var sections = _sectionRepo.GetAll(semester.Id);
        SectionItems = new ObservableCollection<SectionListItemViewModel>(
            sections.Select(s =>
            {
                var vm = new SectionListItemViewModel(
                    s, courseLookup, instructorLookup, roomLookup,
                    sectionTypeLookup, campusLookup,
                    tagLookup, resourceLookup, reserveLookup);
                if (collapsedIds.Contains(s.Id))
                    vm.IsCollapsed = true;
                return vm;
            }));

        // Re-select the specified section so the user can see where it ended up.
        if (selectSectionId is not null)
            SelectedItem = SectionItems.FirstOrDefault(i => i.Section.Id == selectSectionId);
    }

    [RelayCommand]
    private void Add()
    {
        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) return;
        var section = new Section { SemesterId = semester.Id };

        // Use _lastSelectedIndex (captured in OnSelectedItemChanged) because by the
        // time this command runs the ListBox may have already cleared SelectedItem
        // when focus moved to the header Add button.  Place the new section
        // immediately after the last-selected item, or at the end if nothing was
        // ever selected.
        int insertAt = _lastSelectedIndex >= 0 && _lastSelectedIndex < SectionItems.Count
            ? _lastSelectedIndex + 1
            : SectionItems.Count;

        OpenAdd(section, insertAt);
    }

    private void OpenAdd(Section section, int insertIndex)
    {
        // Collapse any currently open editor
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;

        var courses         = _courseRepo.GetAllActive();
        var instructors     = _instructorRepo.GetAll();
        var rooms           = _roomRepo.GetAll();
        var legalStartTimes = _legalStartTimeRepo.GetAll();
        var settings        = AppSettings.Load();
        var includeSaturday = settings.IncludeSaturday;

        var sectionTypes  = _propertyRepo.GetAll(SectionPropertyTypes.SectionType);
        var meetingTypes  = _propertyRepo.GetAll(SectionPropertyTypes.MeetingType);
        var campuses      = _propertyRepo.GetAll(SectionPropertyTypes.Campus);
        var allTags       = _propertyRepo.GetAll(SectionPropertyTypes.Tag);
        var allResources  = _propertyRepo.GetAll(SectionPropertyTypes.Resource);
        var allReserves   = _propertyRepo.GetAll(SectionPropertyTypes.Reserve);

        // Build a minimal placeholder list item so the editor can expand inline.
        var courseLookup     = _courseRepo.GetAll().ToDictionary(c => c.Id);
        var instructorLookup = _instructorRepo.GetAll().ToDictionary(i => i.Id);
        var roomLookup       = _roomRepo.GetAll().ToDictionary(r => r.Id);
        var sectionTypeLookup = sectionTypes.ToDictionary(v => v.Id);
        var campusLookup      = campuses.ToDictionary(v => v.Id);
        var tagLookup         = _propertyRepo.GetAll(SectionPropertyTypes.Tag).ToDictionary(v => v.Id);
        var resourceLookup    = _propertyRepo.GetAll(SectionPropertyTypes.Resource).ToDictionary(v => v.Id);
        var reserveLookup     = _propertyRepo.GetAll(SectionPropertyTypes.Reserve).ToDictionary(v => v.Id);

        var placeholder = new SectionListItemViewModel(
            section, courseLookup, instructorLookup, roomLookup,
            sectionTypeLookup, campusLookup, tagLookup, resourceLookup, reserveLookup);

        // Clamp index in case the list changed between capture and insertion
        if (insertIndex > SectionItems.Count) insertIndex = SectionItems.Count;
        SectionItems.Insert(insertIndex, placeholder);

        var semesterId = _semesterContext.SelectedSemesterDisplay!.Semester.Id;
        var editVm = new SectionEditViewModel(
            section, isNew: true,
            courses, instructors, rooms, legalStartTimes, includeSaturday,
            sectionTypes, meetingTypes, campuses,
            allTags, allResources, allReserves,
            isSectionCodeDuplicate: (courseId, code) =>
                _sectionRepo.ExistsBySectionCode(semesterId, courseId, code, excludeId: null),
            onSave: s =>
            {
                _sectionRepo.Insert(s);
                CollapseEditor();
                Load(selectSectionId: s.Id);
                _scheduleGridVm.Reload();
            },
            _blockPatternRepo,
            defaultBlockLength: settings.PreferredBlockLength);
        editVm.RequestClose = () =>
        {
            // If cancelled, remove the placeholder row
            SectionItems.Remove(placeholder);
            CollapseEditor();
        };

        ExpandedItem = placeholder;
        placeholder.IsExpanded = true;
        EditVm = editVm;
    }

    [RelayCommand]
    private void Edit()
    {
        if (SelectedItem is null) return;
        OpenEdit(CloneSection(SelectedItem.Section), isNew: false, listItem: SelectedItem);
    }

    /// <summary>Called from the view when a list item is double-tapped.</summary>
    public void EditItem(SectionListItemViewModel item)
    {
        SelectedItem = item;

        // Guard: if this item is already open, do nothing.
        //
        // Without this, double-tapping the summary card of an already-open section calls
        // OpenEdit again on the same item. OpenEdit creates a fresh SectionEditViewModel
        // and assigns it to EditVm, which causes the ContentControl to tear down and
        // rebuild its visual tree. During that rebuild Avalonia sets ItemsSource on the
        // single-select ComboBoxes (SectionTypes, Campuses, etc.), but their SelectedValue
        // binding resolves before the items finish populating, so the selection appears
        // blank. A second double-tap repeats the cycle and by coincidence resolves in the
        // correct order — making it look like a toggle. Skipping the rebuild when the item
        // is already expanded eliminates the race entirely.
        if (ExpandedItem == item) return;

        OpenEdit(CloneSection(item.Section), isNew: false, listItem: item);
    }

    /// <summary>
    /// Called from the grid when an entry is double-clicked.
    /// Selects the item in the list and opens its inline editor.
    /// </summary>
    public void EditSectionById(string sectionId)
    {
        var item = SectionItems.FirstOrDefault(i => i.Section.Id == sectionId);
        if (item is null) return;
        EditItem(item);
    }

    private void OpenEdit(Section section, bool isNew, SectionListItemViewModel? listItem)
    {
        // Collapse any currently open editor
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;

        var courses         = _courseRepo.GetAllActive();
        var instructors     = _instructorRepo.GetAll();
        var rooms           = _roomRepo.GetAll();
        var legalStartTimes = _legalStartTimeRepo.GetAll();
        var settings        = AppSettings.Load();
        var includeSaturday = settings.IncludeSaturday;

        var sectionTypes  = _propertyRepo.GetAll(SectionPropertyTypes.SectionType);
        var meetingTypes  = _propertyRepo.GetAll(SectionPropertyTypes.MeetingType);
        var campuses      = _propertyRepo.GetAll(SectionPropertyTypes.Campus);
        var allTags       = _propertyRepo.GetAll(SectionPropertyTypes.Tag);
        var allResources  = _propertyRepo.GetAll(SectionPropertyTypes.Resource);
        var allReserves   = _propertyRepo.GetAll(SectionPropertyTypes.Reserve);

        var semesterId = _semesterContext.SelectedSemesterDisplay!.Semester.Id;
        var editVm = new SectionEditViewModel(
            section, isNew,
            courses, instructors, rooms, legalStartTimes, includeSaturday,
            sectionTypes, meetingTypes, campuses,
            allTags, allResources, allReserves,
            isSectionCodeDuplicate: (courseId, code) =>
                _sectionRepo.ExistsBySectionCode(semesterId, courseId, code, isNew ? null : section.Id),
            onSave: s =>
            {
                if (isNew) _sectionRepo.Insert(s); else _sectionRepo.Update(s);
                CollapseEditor();
                Load(selectSectionId: s.Id);
                _scheduleGridVm.Reload();
            },
            _blockPatternRepo,
            defaultBlockLength: settings.PreferredBlockLength);
        editVm.RequestClose = CollapseEditor;
        ExpandedItem = listItem;
        if (listItem is not null) listItem.IsExpanded = true;
        EditVm = editVm;
    }

    [RelayCommand]
    private async Task Copy()
    {
        if (SelectedItem is null) return;
        var source = SelectedItem.Section;

        var semester = _semesterContext.SelectedSemesterDisplay?.Semester;
        if (semester is null) return;

        // Derive a candidate section code by incrementing the trailing integer suffix, if any.
        string? newCode = null;
        if (!string.IsNullOrEmpty(source.CourseId))
        {
            var match = Regex.Match(source.SectionCode, @"^(.*?)(\d+)$");
            if (match.Success)
            {
                var prefix = match.Groups[1].Value;
                var number = int.Parse(match.Groups[2].Value);
                var candidate = $"{prefix}{number + 1}";
                if (!_sectionRepo.ExistsBySectionCode(semester.Id, source.CourseId, candidate, excludeId: null))
                    newCode = candidate;
                else
                    await (ShowError?.Invoke(
                        $"Could not auto-assign a section code: \"{candidate}\" already exists for this course. " +
                        "The section code has been left blank — please enter one before saving.") ?? Task.CompletedTask);
            }
        }

        var newSection = new Section
        {
            SemesterId = semester.Id,
            CourseId   = source.CourseId,
            SectionCode = newCode ?? string.Empty,
        };

        // Insert the new section immediately after the selected one in the list.
        // We open the editor without pre-inserting — the editor's onSave will insert it.
        // But we need it to appear *below* the selected item, so we insert a placeholder
        // list item first, then open the editor on it.
        OpenCopy(newSection, afterItem: SelectedItem);
    }

    private void OpenCopy(Section section, SectionListItemViewModel afterItem)
    {
        // Collapse any currently open editor
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;

        var courses         = _courseRepo.GetAllActive();
        var instructors     = _instructorRepo.GetAll();
        var rooms           = _roomRepo.GetAll();
        var legalStartTimes = _legalStartTimeRepo.GetAll();
        var settings        = AppSettings.Load();
        var includeSaturday = settings.IncludeSaturday;

        var sectionTypes  = _propertyRepo.GetAll(SectionPropertyTypes.SectionType);
        var meetingTypes  = _propertyRepo.GetAll(SectionPropertyTypes.MeetingType);
        var campuses      = _propertyRepo.GetAll(SectionPropertyTypes.Campus);
        var allTags       = _propertyRepo.GetAll(SectionPropertyTypes.Tag);
        var allResources  = _propertyRepo.GetAll(SectionPropertyTypes.Resource);
        var allReserves   = _propertyRepo.GetAll(SectionPropertyTypes.Reserve);

        // Build a minimal placeholder list item so the editor can expand inline.
        var courseLookup     = _courseRepo.GetAll().ToDictionary(c => c.Id);
        var instructorLookup = _instructorRepo.GetAll().ToDictionary(i => i.Id);
        var roomLookup       = _roomRepo.GetAll().ToDictionary(r => r.Id);
        var sectionTypeLookup = _propertyRepo.GetAll(SectionPropertyTypes.SectionType).ToDictionary(v => v.Id);
        var campusLookup      = _propertyRepo.GetAll(SectionPropertyTypes.Campus).ToDictionary(v => v.Id);
        var tagLookup         = _propertyRepo.GetAll(SectionPropertyTypes.Tag).ToDictionary(v => v.Id);
        var resourceLookup    = _propertyRepo.GetAll(SectionPropertyTypes.Resource).ToDictionary(v => v.Id);
        var reserveLookup     = _propertyRepo.GetAll(SectionPropertyTypes.Reserve).ToDictionary(v => v.Id);

        var placeholder = new SectionListItemViewModel(
            section, courseLookup, instructorLookup, roomLookup,
            sectionTypeLookup, campusLookup, tagLookup, resourceLookup, reserveLookup);

        // Insert immediately after the source item
        int insertIndex = SectionItems.IndexOf(afterItem) + 1;
        SectionItems.Insert(insertIndex, placeholder);

        var semesterId = _semesterContext.SelectedSemesterDisplay!.Semester.Id;
        var editVm = new SectionEditViewModel(
            section, isNew: true,
            courses, instructors, rooms, legalStartTimes, includeSaturday,
            sectionTypes, meetingTypes, campuses,
            allTags, allResources, allReserves,
            isSectionCodeDuplicate: (courseId, code) =>
                _sectionRepo.ExistsBySectionCode(semesterId, courseId, code, excludeId: null),
            onSave: s =>
            {
                _sectionRepo.Insert(s);
                CollapseEditor();
                Load(selectSectionId: s.Id);
                _scheduleGridVm.Reload();
            },
            _blockPatternRepo,
            defaultBlockLength: settings.PreferredBlockLength);
        editVm.RequestClose = () =>
        {
            // If cancelled, remove the placeholder row
            SectionItems.Remove(placeholder);
            CollapseEditor();
        };

        ExpandedItem = placeholder;
        placeholder.IsExpanded = true;
        EditVm = editVm;
    }

    [RelayCommand]
    private void Delete()
    {
        if (SelectedSection is null) return;
        if (ExpandedItem?.Section.Id == SelectedSection.Id)
            CollapseEditor();
        _sectionRepo.Delete(SelectedSection.Id);
        Load();
        _scheduleGridVm.Reload();
    }

    [RelayCommand]
    private void CollapseAll()
    {
        foreach (var item in SectionItems)
            item.IsCollapsed = true;
    }

    [RelayCommand]
    private void ExpandAll()
    {
        foreach (var item in SectionItems)
            item.IsCollapsed = false;
    }

    private void CollapseEditor()
    {
        if (ExpandedItem is not null) ExpandedItem.IsExpanded = false;
        ExpandedItem = null;
        EditVm = null;
    }

    private static Section CloneSection(Section s) => new()
    {
        Id              = s.Id,
        SemesterId      = s.SemesterId,
        CourseId        = s.CourseId,
        InstructorAssignments = s.InstructorAssignments
            .Select(a => new InstructorAssignment { InstructorId = a.InstructorId, Workload = a.Workload })
            .ToList(),
        SectionCode     = s.SectionCode,
        Notes           = s.Notes,
        Schedule        = s.Schedule.Select(d => new SectionDaySchedule
        {
            Day             = d.Day,
            StartMinutes    = d.StartMinutes,
            DurationMinutes = d.DurationMinutes,
            MeetingTypeId   = d.MeetingTypeId,
            RoomId          = d.RoomId,
        }).ToList(),
        SectionTypeId   = s.SectionTypeId,
        CampusId        = s.CampusId,
        TagIds          = new List<string>(s.TagIds),
        ResourceIds     = new List<string>(s.ResourceIds),
        Reserves        = s.Reserves.Select(r => new SectionReserve
            { ReserveId = r.ReserveId, Code = r.Code }).ToList(),
    };
}
